services:

  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:2025.2"
    volumes:
      - ./config:/config
    ports:
      - 8123:8123
    restart: always
